from enum import Enum

class State(Enum):
    CONNECTED = 'CONNECTED'
    MANAGE_DOCTORS = 'MANAGE_DOCTORS'
    HIRE_A_DOCTOR = 'HIRE_A_DOCTOR'
    FIRE_A_DOCTOR = 'FIRE_A_DOCTOR'
    MANAGE_NURSES = 'MANAGE_NURSES'
    HIRE_A_NURSE = 'HIRE_A_NURSE'
    FIRE_A_NURSE = 'FIRE_A_NURSE'
    MANAGE_RECEPTIONISTS = 'MANAGE_RECEPTIONISTS'
    HIRE_A_RECEPTIONIST = 'HIRE_A_RECEPTIONIST'
    FIRE_A_RECEPTIONIST = 'FIRE_A_RECEPTIONIST'