from enum import Enum

class State(Enum):
    CONNECTED = 'CONNECTED'
    MANAGE_EMPLOYEES = 'MANAGE_EMPLOYEES'
    MANAGE_DOCTORS = 'MANAGE_DOCTORS'
    HIRE_A_DOCTOR = 'HIRE_A_DOCTOR'
    FIRE_A_DOCTOR = 'FIRE_A_DOCTOR'
    MANAGE_NURSES = 'MANAGE_NURSES'
    HIRE_A_NURSE = 'HIRE_A_NURSE'
    FIRE_A_NURSE = 'FIRE_A_NURSE'
    MANAGE_RECEPTIONISTS = 'MANAGE_RECEPTIONISTS'
    HIRE_A_RECEPTIONIST = 'HIRE_A_RECEPTIONIST'
    FIRE_A_RECEPTIONIST = 'FIRE_A_RECEPTIONIST'
    MANAGE_PATIENTS = 'MANAGE_PATIENTS'
    AS_A_PATIENT = 'AS_A_PATIENT'
    AS_A_PATIENT_CALL = 'AS_A_PATIENT_CALL'
    AS_A_PATIENT_GO = 'AS_A_PATIENT_GO'
    AS_A_PATIENT_CONFIGURE = 'AS_A_PATIENT_CONFIGURE'
    VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS'

    QUIT = 'QUIT'